export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST'
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOAD_USER = 'LOAD_USER';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

export const  ADD_ALERT = 'ADD_ALERT';
export const  REMOVE_ALERT = 'REMOVE_ALERT';

export const TOKEN_STORAGE_ID = "inventory-token";

export const LOAD_UPC_PRODUCT = 'LOAD_UPC_PRODUCT';

export const ADD_UPC_PRODUCT = 'ADD_UPC_PRODUCT';
export const REMOVE_UPC_PRODUCT = "REMOVE_UPC_PRODUCT";

export const ADD_USER_PRODUCT = "ADD_USER_PRODUCT"

export const LOAD_USER_PRODUCT = "LOAD_USER_PRODUCT"

export const UPDATE_USER_PRODUCT = "UPDATE_USER_PRODUCT"

export const DELETE_USER_PRODUCT = "DELETE_USER_PRODUCT"
export const REMOVE_USER_PRODUCT = "REMOVE_USER_PRODUCT";

